
NOT_AVAILABLE_IAP "erkjjhzd" // Some IAP which is not available but is configured in the phone

SYNC 0
ASYNC 1
PAUSE 4000

KIptvVodContentCategoryRootId 0

KErrNone 0
KErrCancel -3

EIgnoreUpdateNotStarted 1
EBriefContentDetails    2
EUpdateSucceedsAlways   3



LOOP_CNT_WLAN 		15
LOOP_CNT_3G		5

PAUSE_MS	5000
PAUSE_SEC 10000
PAUSE_SEC2 5000

EBriefContentDetails 	2

SERVICE_INVALID_PASSWORD "InvalidPassword"
SERVICE_INVALID_URL1 "InvalidUrl1"
SERVICE_INVALID_URL2 "InvalidUrl2"
SERVICE_INVALID_URL3 "InvalidUrl3"


KBadCharacters      6001

SEARCH_CONTENT_1          1000001
SEARCH_CONTENT_2          1000002
SEARCH_CONTENT_3          1000003
SEARCH_CONTENT_4          1000004
SEARCH_CONTENT_5          1000005
SEARCH_CONTENT_6          1000006
SEARCH_CONTENT_7          1000007
SEARCH_CONTENT_8          1000008
SEARCH_CONTENT_9          1000009


KIptvTestSearchCategoryId -3
KIptvRssSearchContentId1 1000001
KIptvRssSearchContentId2 1000002
KIptvRssSearchContentId3 1000003
KIptvRssSearchContentId4 1000004
KIptvRssSearchContentId5 1000005

TN_0 "6c822b9953c889870be1edda8dded078.png"
TN_1 "43d57eac6eda476dc1b7e5f28116a63a.png"
TN_2 "373e2acbd2d3b65d62628bbb319cad7d.png"
TN_3 "fca2e22fbec251675ab8a2bd810ac542.png"
TN_4 "c40e76620d22f6868cbd1736c3397c3c.png"
TN_5 "2ccd2fc80705d5696ea553bd2250f650.png"
TN_6 "a6fca05862e077c9281dbeca054e0884.png"
TN_7 "15002c90a612811e8a1aa9368d86f4aa.png"
TN_8 "ee037799f9dd4799eff888e8febcbc45.png"

SERVICE_TN "Thumbnail service"
