
SERVICE_URL_SERVICE_1 "http:\/\/193.65.182.78/nokia_vod.xml"
SERVICE_URL_SERVICE_2 "http:\/\/193.65.182.78/testingfeed_iptvengine.xml"
SERVICE_URL_BADSRVURL "http:\/\/www.badurl_qwer123.com/service.xml"
SERVICE_URL_500VIDEOS "http:\/\/193.65.182.78/huge/500videos.xml"
SERVICE_URL_UNTYPICAL "http:\/\/193.65.182.78/untypical.xml"
SERVICE_URL_NA_VIDEOS "http:\/\/193.65.182.78/nafiles.xml"
SERVICE_URL_W_STREAMS "http:\/\/193.65.182.78/streamsandcodecs_categories.xml"
SERVICE_URL_XMLTV_SRV "http:\/\/mediacharger.wipsl.com/epg_iptv/epg_iptv.xml"
